baseurl = "https://rmartins-uab.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
title = "CabraCega"


[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

